os:
  - linux
language: java
node_js:
  - "10"
jdk:
  - openjdk8
sudo: false
cache:
  directories:
    - node
    - node_modules
    - $HOME/.m2
env:
  - NODE_VERSION=10.7.0
before_install:
  - nvm install $NODE_VERSION
  - npm install -g npm@6.1.0
  - npm install -g n
  - sudo n stable
  - npm install -g bower@1.7.9
  - npm install -g gulp-cli@2.2.1
  - node -v
  - npm -v
  - bower -v
  - gulp -v
  - java -version
install: npm install
script:
  - ./mvnw clean
  - ./mvnw package -Pprod -DskipTests
notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
