INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (2,1,3, 'STRUCTURE_BURNIN', 'Length of burnin period', false, 'ENTERO', '10000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (3,1,3, 'STRUCTURE_NUMREPS', 'Number of MCMC reps after burnin', false, 'ENTERO', '20000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (4,1,3, 'STRUCTURE_PLOIDY', 'Ploidy of data', false, 'ENTERO', '2');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (5,1,3, 'STRUCTURE_MISSING', 'Value given to missing genotype data', true, 'ENTERO', '-9');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (6,1,3, 'STRUCTURE_ONEROWPERIND', 'Store data for individuals in a single line', true, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (7,1,3, 'STRUCTURE_LABEL', 'Input file contains individual labels', true, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (8,1,3, 'STRUCTURE_POPDATA', 'Input file contains a population identifier', true, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (9,1,3, 'STRUCTURE_POPFLAG', 'Input file contains a flag which says whether to use popinfo when USEPOPINFO==1', true, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (10,1,3, 'STRUCTURE_LOCDATA', 'Input file contains a location identifier', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (11,1,3, 'STRUCTURE_PHENOTYPE', 'Input file contains phenotype information', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (12,1,3, 'STRUCTURE_EXTRACOLS', 'Number of additional columns of data before the genotype data start.', true, 'ENTERO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (13,1,3, 'STRUCTURE_MARKERNAMES', 'Data file contains row of marker names', true, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (14,1,3, 'STRUCTURE_RECESSIVEALLELES', 'Data file contains dominant markers (eg AFLPs) and a row to indicate which alleles are recessive', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (15,1,3, 'STRUCTURE_MAPDISTANCES', 'Data file contains row of map distances between loci', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (16,1,3, 'STRUCTURE_PHASED', 'Data are in correct phase (relevant for linkage model only)', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (17,1,3, 'STRUCTURE_PHASEINFO', 'The data for each individual contains a line indicating phase (linkage model)', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (18,1,3, 'STRUCTURE_MARKOVPHASE', 'The phase info follows a Markov model.', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (19,1,3, 'STRUCTURE_NOTAMBIGUOUS', 'For use in some analyses of polyploid data', true, 'ENTERO', '-9');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (20,1,4, 'STRUCTURE_STRUCTURE_NOADMIX', 'Use no admixture model (0=admixture model, 1=no-admix)', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (21,1,4, 'STRUCTURE_LINKAGE', 'Use the linkage model', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (22,1,4, 'STRUCTURE_USEPOPINFO', 'Use prior population information to pre-assign individuals to clusters', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (23,1,4, 'STRUCTURE_LOCPRIOR', 'Use location information to improve weak data', true, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (24,1,4, 'STRUCTURE_FREQSCORR', 'Allele frequencies are correlated among pops', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (25,1,4, 'STRUCTURE_ONEFST', 'Assume same value of Fst for all subpopulations', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (26,1,4, 'STRUCTURE_INFERALPHA', 'Infer ALPHA (the admixture parameter)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (27,1,4, 'STRUCTURE_POPALPHAS', 'Individual alpha for each population', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (28,1,4, 'STRUCTURE_ALPHA', 'Dirichlet parameter for degree of admixture (this is the initial value if INFERALPHA==1).', false, 'NUMERICO', '1.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (29,1,4, 'STRUCTURE_INFERLAMBDA', 'Infer LAMBDA (the allele frequencies parameter)', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (30,1,4, 'STRUCTURE_POPSPECIFICLAMBDA', 'Infer a separate lambda for each pop (only if INFERLAMBDA=1)', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (31,1,4, 'STRUCTURE_LAMBDA', 'Dirichlet parameter for allele frequencies', false, 'NUMERICO', '1.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (32,1,4, 'STRUCTURE_FPRIORMEAN', 'Prior mean and SD of Fst for pops.', false, 'NUMERICO', '0.01');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (33,1,4, 'STRUCTURE_FPRIORSD', 'The prior is a Gamma distribution with these parameters', false, 'NUMERICO', '0.05');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (34,1,4, 'STRUCTURE_UNIFPRIORALPHA', 'Use a uniform prior for alpha otherwise gamma prior', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (35,1,4, 'STRUCTURE_ALPHAMAX', 'Max value of alpha if uniform prior', false, 'NUMERICO', '10.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (36,1,4, 'STRUCTURE_ALPHAPRIORA', '(only if UNIFPRIORALPHA==0): alpha has a gamma prior with mean A*B, and variance A*B^2.', false, 'NUMERICO', '1.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (37,1,4, 'STRUCTURE_ALPHAPRIORB', '(only if UNIFPRIORALPHA==0): alpha has a gamma prior with mean A*B, and variance A*B^2.', false, 'NUMERICO', '2.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (38,1,4, 'STRUCTURE_LOG10RMIN', 'Log10 of minimum allowed value of r under linkage model', false, 'NUMERICO', '-4.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (39,1,4, 'STRUCTURE_LOG10RMAX', 'Log10 of maximum allowed value of r', false, 'NUMERICO', '1.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (40,1,4, 'STRUCTURE_LOG10RPROPSD', 'Standard deviation of log r in update', false, 'NUMERICO', '0.1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (41,1,4, 'STRUCTURE_LOG10RSTART', 'Initial value of log10 r', false, 'NUMERICO', '-2.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (42,1,4, 'STRUCTURE_GENSBACK', 'For use when inferring whether an individual is an immigrant, or has an immigrant an-GENSBACK==2, it tests for immigrant ancestry back to grandparents.', false, 'ENTERO', '2');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (43,1,4, 'STRUCTURE_MIGRPRIOR', 'Prior prob that an individual is a migrant (used only when USEPOPINFO==1).  This should be small, eg 0.01 or 0.1.', false, 'NUMERICO', '0.01');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (44,1,4, 'STRUCTURE_PFROMPOPFLAGONLY', 'Only use individuals with POPFLAG=1 to update	P. This is to enable use of a reference set of  individuals for clustering additional \"test\" individuals.', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (45,1,4, 'STRUCTURE_LOCISPOP', 'Use POPDATA for location information', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (46,1,4, 'STRUCTURE_LOCPRIORINIT', 'Initial value for r, the location prior', false, 'NUMERICO', '1.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (47,1,4, 'STRUCTURE_MAXLOCPRIOR', 'Max allowed value for r', false, 'NUMERICO', '20.0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (48,1,4, 'STRUCTURE_PRINTNET', 'Print the \"net nucleotide distance\" to screen during the run', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (49,1,4, 'STRUCTURE_PRINTLAMBDA', 'Print current value(s) of lambda to screen', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (50,1,4, 'STRUCTURE_PRINTQSUM', 'Print summary of current population membership to screen', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (51,1,4, 'STRUCTURE_SITEBYSITE', 'Whether or not to print site by site results (Linkage model only)', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (52,1,4, 'STRUCTURE_PRINTQHAT', 'Q-hat printed to a separate file.  Turn this on before using STRAT.', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (53,1,4, 'STRUCTURE_UPDATEFREQ', 'Frequency of printing update on the screen. Set automatically if this is 0.', false, 'ENTERO', '100');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (54,1,4, 'STRUCTURE_PRINTLIKES', 'Print current likelihood to screen every rep', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (55,1,4, 'STRUCTURE_INTERMEDSAVE', 'Number of saves to file during run', false, 'ENTERO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (56,1,4, 'STRUCTURE_ECHODATA', 'Print some of data file to screen to check that the data entry is correct.', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (57,1,4, 'STRUCTURE_ANCESTDIST', 'Collect data about the distribution of ancestry coefficients (Q) for each individual', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (58,1,4, 'STRUCTURE_NUMBOXES', 'The distribution of Q values is stored as a histogram with this number of boxes.', false, 'ENTERO', '1000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (59,1,4, 'STRUCTURE_ANCESTPINT', 'The size of the displayed probability interval on Q (values between 0.0--1.0)', false, 'NUMERICO', '0.90');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (60,1,4, 'STRUCTURE_COMPUTEPROB', 'Estimate the probability of the Data under  the model.  This is used when choosing the best number of subpopulations.', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (61,1,4, 'STRUCTURE_ADMBURNIN', '[only relevant for linkage model]:  Initial period of burnin with admixture model', false, 'ENTERO', '500');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (62,1,4, 'STRUCTURE_ALPHAPROPSD', 'SD of proposal for updating alpha', false, 'NUMERICO', '0.025');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (63,1,4, 'STRUCTURE_STARTATPOPINFO', 'Use given populations as the initial condition for population origins.  (Need POPDATA==1).  It                               is assumed that the PopData in the input file are between 1 and k where k<=MAXPOPS.', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (64,1,4, 'STRUCTURE_RANDOMIZE', 'Use new random seed for each run', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (65,1,4, 'STRUCTURE_SEED', 'Seed value for random number generator (must set RANDOMIZE=0)', false, 'ENTERO', '2245');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (66,1,4, 'STRUCTURE_METROFREQ', 'Frequency of using Metropolis step to update Q under admixture model (ie use the metr. move everyi steps).  If this is set to 0, it is never used. (Proposal for each q^(i) sampled from prior.  The goal is to improve mixing for small alpha.)', false, 'ENTERO', '10');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (67,1,4, 'STRUCTURE_REPORTHITRATE', 'report hit rate if using METROFREQ', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (69,1,5, 'DISTRUCT_DISTRUCT_PRINT_LABEL_ATOP', 'Print labels above figure', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (70,1,5, 'DISTRUCT_PRINT_LABEL_BELOW', 'print labels below figure', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (71,1,5, 'DISTRUCT_PRINT_SEP', 'print lines to separate populations', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (72,1,5, 'DISTRUCT_FONTHEIGHT', 'size of font', false, 'NUMERICO', '6');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (73,1,5, 'DISTRUCT_DIST_ABOVE', 'distance above plot to place text', false, 'NUMERICO', '5');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (74,1,5, 'DISTRUCT_DIST_BELOW', 'distance below plot to place text', false, 'NUMERICO', '-7');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (75,1,5, 'DISTRUCT_BOXHEIGHT', 'height of the figure', false, 'NUMERICO', '36');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (76,1,5, 'DISTRUCT_INDIVWIDTH', 'width of an individual', false, 'NUMERICO', '1.5');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (77,1,5, 'DISTRUCT_ORIENTATION', '0 for horizontal orientation (default) , 1 for vertical orientation,  2 for reverse horizontal orientation', false, 'ENTERO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (78,1,5, 'DISTRUCT_XORIGIN', 'lower-left x-coordinate of figure', false, 'NUMERICO', '70');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (79,1,5, 'DISTRUCT_YORIGIN', 'lower-left y-coordinate of figure', false, 'NUMERICO', '10');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (80,1,5, 'DISTRUCT_XSCALE', 'scale for x direction', false, 'NUMERICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (81,1,5, 'DISTRUCT_YSCALE', 'scale for y direction', false, 'NUMERICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (82,1,5, 'DISTRUCT_ANGLE_LABEL_ATOP', 'angle for labels atop figure (in [0,180])', false, 'NUMERICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (83,1,5, 'DISTRUCT_ANGLE_LABEL_BELOW', 'angle for labels below figure (in [0,180])', false, 'NUMERICO', '90');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (84,1,5, 'DISTRUCT_LINEWIDTH_RIM', 'width of \"pen\" for rim of box', false, 'NUMERICO', '3');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (85,1,5, 'DISTRUCT_LINEWIDTH_SEP', 'width of \"pen\" for separators between pops and for tics', false, 'NUMERICO', '0.3');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (86,1,5, 'DISTRUCT_LINEWIDTH_IND', 'width of \"pen\" used for individuals', false, 'NUMERICO', '0.3');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (87,1,5, 'DISTRUCT_GRAYSCALE', 'use grayscale instead of colors', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (88,1,5, 'DISTRUCT_ECHO_DATA', 'print some of the data to the screen', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (89,1,5, 'DISTRUCT_REPRINT_DATA', 'print the data as a comment in the ps file', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (90,1,5, 'DISTRUCT_PRINT_INFILE_NAME', 'print the name of INFILE_POPQ above the figure this option is meant for use only with ORIENTATION=0', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (91,1,5, 'DISTRUCT_PRINT_COLOR_BREWER', 'print ColorBrewer settings in the output file this option adds 1689 lines and 104656 bytes to the output and is required if using ColorBrewer colors', false, 'LOGICO', '1');




INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (105,1,2, 'STRUCTURE_K_DESDE', 'Valor inicial de K para la ejecución de Structure', false, 'ENTERO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (106,1,2, 'STRUCTURE_K_HASTA', 'Valor final de K para la ejecución de Structure', false, 'ENTERO', '4');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (107,1,2, 'STRUCTURE_REPLICAS', 'Cantidad de replicas por K para la ejecución de Structure', false, 'ENTERO', '3');


INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (108,2,7, 'GENEPOP_OP_1.1', 'HW test for each locus in each population: H1 = Heterozygote deficiency', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (109,2,7, 'GENEPOP_OP_1.2', 'HW test for each locus in each population: H1 = Heterozygote excess', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (110,2,7, 'GENEPOP_OP_1.3', 'HW test for each locus in each population: Probability test', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (111,2,7, 'GENEPOP_OP_1.4', 'Global test: H1 = Heterozygote deficiency', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (112,2,7, 'GENEPOP_OP_1.5', 'Global test: H1 = Heterozygote excess', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (113,2,7, 'GENEPOP_OP_2.1', 'Pairwise associations (haploid and genotypic disequilibrium): Test for each pair of loci in each population', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (114,2,7, 'GENEPOP_OP_2.2', 'Pairwise associations (haploid and genotypic disequilibrium): Only create genotypic contingency tables', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (115,2,7, 'GENEPOP_OP_3.1', 'Genic differentiation: for all populations', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (116,2,7, 'GENEPOP_OP_3.2', 'Genic differentiation: for all pairs of populations', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (117,2,7, 'GENEPOP_OP_3.3', 'Genotypic differentiation: for all populations', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (118,2,7, 'GENEPOP_OP_3.4', 'Genotypic differentiation: for all pairs of populations', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (119,2,7, 'GENEPOP_OP_5.1', 'Allele and genotype frequencies per locus and per sample', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (120,2,7, 'GENEPOP_OP_5.2', 'Gene diversities & Fis: Using allele identity', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (121,2,7, 'GENEPOP_OP_5.3', 'Gene diversities & Fis: Using allele size', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (122,2,7, 'GENEPOP_OP_6.1', 'Estimating spatial structure: Allele identity (F-statistics) for all populations', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (123,2,7, 'GENEPOP_OP_6.2', 'Estimating spatial structure: Allele identity (F-statistics) for all population pairs', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (124,2,7, 'GENEPOP_OP_6.3', 'Estimating spatial structure: Allele size (Rho-statistics) for all populations', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (125,2,7, 'GENEPOP_OP_6.4', 'Estimating spatial structure: Allele size (Rho-statistics) for all population pairs', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (126,2,7, 'GENEPOP_OP_8.1', 'Null allele: estimates of allele frequencies', false, 'LOGICO', '1');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (127,2,8, 'GENEPOP_Dememorisation', 'Dememorisation', false, 'ENTERO', '10000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (128,2,8, 'GENEPOP_BatchLength', 'BatchLength', false, 'ENTERO', '5000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (129,2,8, 'GENEPOP_BatchNumber', 'BatchNumber', false, 'ENTERO', '20');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (130,2,8, 'GENEPOP_HWtests', 'HWtests', false, 'CARACTER', 'Enumeration');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (131,2,8, 'GENEPOP_Mode', 'Mode', true, 'CARACTER', 'Batch');


INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (132,1,6, 'CLUMPP_M', 'Method to be used (1 = FullSearch, 2 = Greedy, 3 = LargeKGreedy).', false, 'ENTERO', '3');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (133,1,6, 'CLUMPP_W', 'Weight by the number of individuals in each population as specified in the datafile.', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (134,1,6, 'CLUMPP_S', 'Pairwise matrix similarity statistic to be used. 1 = G, 2 = G'' ', false, 'ENTERO', '2');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (135,1,6, 'CLUMPP_GREEDY_OPTION', '(Only options 1 and 2 are supported) 1 = All possible input orders, 2 = random input orders, 3 = pre-specified input orders.', false, 'ENTERO', '2');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (136,1,6, 'CLUMPP_REPEATS', 'If GREEDY_OPTION = 2, then REPEATS determines the number of random input orders to be tested. If GREEDY_OPTION = 3, then REPEATS is the number of input orders in PERMUTATIONFILE. ', false, 'ENTERO', '1000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (137,1,6, 'CLUMPP_PRINT_PERMUTED_DATA', 'Print the permuted data (clusters) in INDFILE or POPFILE to PERMUTED_DATAFILE (0 = don''t print, 1 = print into one file, 2 = print into separate files for each run).', false, 'ENTERO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (138,1,6, 'CLUMPP_PRINT_EVERY_PERM', 'Print every tested permutation of the runs and the corresponding value of SSC to a file specified by EVERY_PERMFILE (0 = don''t print, 1 = print). Note that printing may result in a very large file.', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (139,1,6, 'CLUMPP_PRINT_RANDOM_INPUTORDER', 'Print random input orders of runs to RANDOM_INPUTORDER (0 = don''t print, 1 = print). This option is only available if GREEDY_OPTION = 2.', false, 'LOGICO', '0');


INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (140,1,2, 'STRUCTURE_HILOS', 'Cantidad de hilos de ejecución para Structure. (0 indica todos los disponibles)', false, 'ENTERO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (141,1,2, 'STRUCTURE_COLOR_EVANNO_DELTA_K', 'Color de las lineas y puntos del gráfico de Evanno, Delta K vs K', false, 'CARACTER', '#0099FF');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (142,3,1, 'DAPC_LEYENDA_CONJUNTO', 'Atributo de los Conjuntos de Muestras a utilizar como leyenda [detalle, codigo, id]', false, 'CARACTER', 'detalle');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (143,3,1, 'DAPC_SCALE', 'Indica si las variables deben ser escaladas', false, 'LOGICO', '0');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (144,3,9, 'DAPC_FC_PERC_PCA', 'Porcentaje mínimo de la varianza total. Si DAPC_FC_N_PCA es distinto de 0 este parámetro debe ser 0. (función adegenet/find.clusters:perc.pca)', false, 'NUMERICO', '95');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (145,3,9, 'DAPC_FC_N_PCA', 'Número de ejes retenidos en el PCA. Si DAPC_FC_PERC_PCA es distinto de 0 este parámetro debe ser 0. (función adegenet/find.clusters:n.pca)', false, 'ENTERO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (146,3,9, 'DAPC_FC_EJECUTAR', 'Indica si se determinará la cantidad de grupos (K) (función adegenet/find.clusters)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (147,3,9, 'DAPC_FC_METHOD', 'Método de agrupamiento [kmeans, ward] (función adegenet/find.clusters:method)', false, 'CARACTER', 'kmeans');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (148,3,9, 'DAPC_FC_STAT', 'Estadístico a utilizar [BIC, AIC, WSS] (función adegenet/find.clusters:stat)', false, 'CARACTER', 'BIC');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (149,3,9, 'DAPC_FC_CRITERION', 'Criterio de selección de K [diffNgroup, min, goesup, smoothNgoesup, goodfit] (función adegenet/find.clusters:criterion)', false, 'CARACTER', 'diffNgroup');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (150,3,9, 'DAPC_FC_N_ITER', 'Cantidad de iteraciones usadas con kmeans (función adegenet/find.clusters:n.iter)', false, 'ENTERO', '10000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (151,3,9, 'DAPC_FC_N_STAR', 'Cantidad inicial de centroides de kmeans (función adegenet/find.clusters:n.start)', false, 'ENTERO', '10');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (152,3,9, 'DAPC_FC_PLOT_COL_BASE', 'Color base utilizado en el gráfico del estadístico vs K', false, 'CARACTER', '#0099FF');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (153,3,9, 'DAPC_FC_PLOT_COL_SEL', 'Color del K seleccionado en el gráfico del estadístico vs K', false, 'CARACTER', 'red');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (154,3,9, 'DAPC_FC_K_MAX', 'Valor máximo de K a analizar. Si es 0 se calculará como el valor entero de la cantidad de muestras sobre diez. (función adegenet/find.clusters:max.n.clust)', false, 'ENTERO', '0');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (155,3,10, 'DAPC_CV_NCPUS', 'Cantidad de hilos de ejecución (si se encuentra instalado OMP dejar en 0) (función adegenet/xvalDapc:ncpus)', false, 'ENTERO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (156,3,10, 'DAPC_CV_NA_METHOD', 'Método utilizado para reemplazar valores nulos [mean, zero] (función adegenet/tab:NA.method)', false, 'CARACTER', 'mean');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (157,3,10, 'DAPC_CV_REP', 'Cantidad de repeticiones de la validación cruzada (función adegenet/xvalDapc:n.rep)', false, 'ENTERO', '30');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (158,3,10, 'DAPC_CV_EXP', 'Valor que se usará para determinar el rango de PCs a evaluar en la segunda validación cruzada (VC) (rango a evaluar = mejor PC de la VC 1 +- DAPC_CV_EXP)', false, 'ENTERO', '5');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (159,3,10, 'DAPC_CV_TRAINING_SET', 'Porcentaje de las muestras que se utilizarán para el conjunto de entrenamiento (función adegenet/xvalDapc:training.set)', false, 'NUMERICO', '0.9');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (160,3,10, 'DAPC_CV_RESULT', 'Método de predicción [groupMean, overall] (función adegenet/xvalDapc:result)', false, 'CARACTER', 'groupMean');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (161,3,11, 'DAPC_SP_LEGEND', 'Indica si se visualizan las leyendas (función adegenet/scatter:legend)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (162,3,11, 'DAPC_SP_CLABEL', 'Indica si se visualizan las etiquetas (función adegenet/scatter:legend)', false, 'LOGICO', '0');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (163,3,11, 'DAPC_SP_SCREE_PCA', 'Indica si se visualizan los PCA (función adegenet/scatter:scree.pca)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (164,3,11, 'DAPC_SP_SCREE_DA', 'Indica si se visualizan los DA (función adegenet/scatter:scree.da)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (165,3,11, 'DAPC_SP_POSI_LEG', 'Posición de las leyendas [bottomleft, bottomright, topleft, topright] (función adegenet/scatter:posi.leg)', false, 'CARACTER', 'bottomleft');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (166,3,11, 'DAPC_SP_POSI_PCA', 'Posición de los PCA [bottomleft, bottomright, topleft, topright] (función adegenet/scatter:posi.pca)', false, 'CARACTER', 'topleft');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (167,3,11, 'DAPC_SP_POSI_DA', 'Posición de los DA [bottomleft, bottomright, topleft, topright] (función adegenet/scatter:posi.da)', false, 'CARACTER', 'bottomright');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (168,3,11, 'DAPC_SP_POSI_CLEG', 'Tamaño de la letra de las leyendas (función adegenet/scatter:cleg)', false, 'ENTERO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (169,3,11, 'DAPC_SP_P_IND_IMP_MUESTRAS', 'Indica si se imprimen los ID de las Muestras en el gráfico de asignación a nivel de muestra', false, 'LOGICO', '1');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (170,3,12, 'DAPC_LP_UMBRAL', 'Valor del cuantil sobre el cual se visualizarán los nombres de las variables (función adegenet/loadingplot:thres)', false, 'NUMERICO', '0.95');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (171,3,1, 'DAPC_TIPO_LOCI', 'Tipo de loci a estudiar [codom, PA] (función adegenet/df2genind:type)', false, 'CARACTER', 'codom');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (172,4,1, 'IND_VAL_LEYENDA_CONJUNTO', 'Atributo de los Conjuntos de Muestras a utilizar como leyenda [detalle, codigo, id]', false, 'CARACTER', 'detalle');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (173,4,1, 'IND_VAL_TIPO_LOCI', 'Tipo de loci a estudiar [codom, PA] (función adegenet/df2genind:type)', false, 'CARACTER', 'codom');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (174,4,13, 'IND_VAL_GEN_CURV', 'Indica si se genera la curva de genotipos (función poppr/genotype_curve)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (175,4,13, 'IND_VAL_GEN_CURV_SAMPLE', 'Cantidad de muestras para la generación de la curva de genotipos (función poppr/genotype_curve:sample)', false, 'ENTERO', '1000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (176,4,1, 'IND_VAL_PLOIDY', 'Indica si se genera el gráfico de ploidía (función poppr/info_table:type=ploidy)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (177,4,1, 'IND_VAL_MISSING', 'Indica si se genera el gráfico de alelos perdidos (función poppr/info_table:type=missing)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (178,4,14, 'IND_VAL_DIVERSITY', 'Indica si se genera la tabla con los indices de diversidad (función poppr/poppr)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (179,4,14, 'IND_VAL_DIVERSITY_SAMPLE', 'Cantidad de muestras para la generación de la tabla de indices de diversidad (función poppr/poppr:sample)', false, 'ENTERO', '1000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (180,4,14, 'IND_VAL_DIVERSITY_INDEX', 'Índice que se utilizará para la generación del histograma [rbarD, Ia] (función poppr/poppr:index)', false, 'CARACTER', 'rbarD');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (181,4,1, 'IND_VAL_MLG', 'Indica si se genera la tabla y gráficos de MLG (Multilocus Genotypes) (función poppr/mlg.table)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (182,4,15, 'IND_VAL_HW', 'Indica si se generan las tablas y gráficos de Hardy - Weinberg (por ahora solo disponible para Loci diploides) (función pegas/hw.test)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (183,4,15, 'IND_VAL_HW_STAT', 'Método utilizado para determinar el P-Value en el gráfico de Hardy - Weinberg (Loci) [chi2: Chi-Cuadrado, MC: Monte Carlo] (función pegas/hw.test)', false, 'CARACTER', 'chi2');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (184,4,15, 'IND_VAL_HW_STAT_MC_SAMPLE', 'Cantidad de réplicas utilizadas en el método de Monte Carlo en Hardy - Weinberg (función pegas/hw.test)', false, 'ENTERO', '1000');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (185,4,15, 'IND_VAL_HW_ALFA', 'Umbral sobre el P-Value utilizado en el gráfico de Hardy - Weinberg (Loci)', false, 'NUMERICO', '0.05');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (186,4,16, 'IND_VAL_LOCUS_TABLE', 'Indica si se genera la tabla con los indices de diversidad por Loci (función poppr/locus_table)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (187,4,16, 'IND_VAL_LOCUS_TABLE_INDEX', 'Índice que se utilizará en la tabla de diversidad por Loci [simpson, shannon, invsimpson] (función poppr/locus_table:index)', false, 'CARACTER', 'simpson');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (188,4,16, 'IND_VAL_LOCUS_TABLE_LEV', 'Nivel al que se generará la tabla de diversidad por Loci [allele, genotype] (función poppr/locus_table:lev)', false, 'CARACTER', 'allele');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (189,4,17, 'IND_VAL_ALELOS_EJECUTAR', 'Indica si se generarán los graficos y tablas a nivel de Alelos (función poppr/tab)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (190,4,17, 'IND_VAL_ALELOS_FREC', 'Indica si se generarán los graficos y tablas de frecuencias de Alelos', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (191,4,17, 'IND_VAL_ALELOS_PROM', 'Indica si se generarán los graficos y tablas de la cantidad promedio de Alelos', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (192,4,17, 'IND_VAL_ALELOS_NA_METHOD', 'Método con el que se tratarán los valores nulos en los graficos y tablas de Alelos [mean, zero] (función poppr/tab:NA.method)', false, 'CARACTER', 'mean');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (193,4,1, 'IND_VAL_BASIC_STATS', 'Indica si se genera la tabla valores estadístico básicos (Fit, Fst, Fis, etc) (función hierfstat/basic.stats)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (194,4,1, 'IND_VAL_ALLELIC_RICHNESS', 'Indica si se genera la tabla de riqueza alélica (solo disponible para diploides) (función hierfstat/allelic.richness)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (196,4,18, 'IND_VAL_DIST_POP', 'Indica si se genera la tabla de distancia entre Conjuntos de Muestras (función adegenet/dist.genpop)', false, 'LOGICO', '1');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (197,4,18, 'IND_VAL_DIST_POP_METHOD', 'Función de distancia a utilizar [1:Nei, 2:Edwards, 3:Reynolds, 4:Rogers, 5:Provesti] (función adegenet/dist.genpop:method)', false, 'ENTERO', '1');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (198,3,9, 'DAPC_FC_K', 'Valor de K a analizar. Si es 0 se determinará automaticamente a partir del estadístico y criterio indicado. (función adegenet/find.clusters:n.clust)', false, 'ENTERO', '0');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (199,3,11, 'DAPC_SP_P_IND_XLEN', 'Gráfico de asignación a nivel de muestra: tamaño del texto del eje X', false, 'ENTERO', '7');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (200,3,11, 'DAPC_SP_P_IND_YLEN', 'Gráfico de asignación a nivel de muestra: tamaño del texto del eje Y', false, 'ENTERO', '12');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (201,3,11, 'DAPC_SP_P_IND_TLEN', 'Gráfico de asignación a nivel de muestra: tamaño del texto de las leyendas', false, 'ENTERO', '15');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (202,3,11, 'DAPC_SP_P_IND_NCOL', 'Gráfico de asignación a nivel de muestra: cantidad de columnas', false, 'ENTERO', '1');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (203,3,11, 'DAPC_SP_P_BOX_XLEN', 'Gráfico de asignación a nivel de conjunto de muestras: tamaño del texto del eje X', false, 'ENTERO', '12');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (204,3,11, 'DAPC_SP_P_BOX_YLEN', 'Gráfico de asignación a nivel de conjunto de muestras: tamaño del texto del eje Y', false, 'ENTERO', '12');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (205,3,11, 'DAPC_SP_P_BOX_TLEN', 'Gráfico de asignación a nivel de conjunto de muestras: tamaño del texto de las leyendas', false, 'ENTERO', '15');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (206,3,11, 'DAPC_SP_P_BOX_NCOL', 'Gráfico de asignación a nivel de conjunto de muestras: cantidad de columnas', false, 'ENTERO', '1');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (207,3,9, 'DAPC_FC_PLOT_XLEN', 'Gráfico del estadístico vs K:  tamaño del texto del eje X', false, 'ENTERO', '18');
INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (208,3,9, 'DAPC_FC_PLOT_YLEN', 'Gráfico del estadístico vs K:  tamaño del texto del eje Y', false, 'ENTERO', '18');

INSERT INTO parametros_procedimientos (id, procedimiento_id,categoria_id,codigo,detalle,no_editable,tipo,valor) VALUES (209,1,2, 'STRUCTURE_GEN_LOGS', 'Indica si se generan los archivos de logs de la ejecución de Structure', false, 'LOGICO', '0');

SELECT pg_catalog.setval('parametros_procedimientos_id_seq', 209, true);

